// MODAL LOGIN
export const TOOGLE = `MODAL: TOOGLE`;
export const TOOGLE_LOGIN = `MODAL: TOOGLE_LOGIN`;
export const SIGNUP_RESPONSE = `MODAL: SIGNUP_RESPONSE`;
export const SIGNIN_RESPONSE = `MODAL: SIGNIN_RESPONSE`;

export const SERVER_ERROR = `MODAL: SERVER_ERROR`;
export const CLEAR_NOTIFICATION = `MODAL: CLEAR_NOTIFICATION`;

export const EXAMPLE = `EXAMPLE`;

// User
export const AUTH_SUCCESS = `SESSION: AUTH_SUCCESS`;
export const LOG_OUT = `SESSION: LOG_OUT`;

// Bets
export const BET_APLLY = 'BET: APLLY';
export const BET_FETCH_SUCCESS = 'BET: FETCH_SUCCESS';
export const BET_FETCH_FAILURE = 'BET: FETCH_FAILURE';
